singleuser:
  image:
    name: tjcrone/pangeo-notebook
    tag: 616f145
  cmd: ['start-singleuser.sh']
#  extraEnv:
#    EXTRA_PIP_PACKAGES: >-
#    GCSFUSE_BUCKET: pangeo-data
#  storage:
#    extraVolumes:
#      - name: fuse
#        hostPath:
#          path: /dev/fuse
#    extraVolumeMounts:
#      - name: fuse
#        mountPath: /dev/fuse
  cpu:
    limit: 1.8
    guarantee: 0.9
  memory:
    limit: 8G
    guarantee: 4G

rbac:
  enabled: false

hub:
  extraConfig: |
    c.KubeSpawner.singleuser_service_account = 'default'
    c.KubeSpawner.start_timeout = 60 * 10 # 10-minute timeout for Azure
    c.Spawner.default_url = '/lab'
    c.Spawner.cmd = ['jupyter-labhub']
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook

cull:
  enabled: true
  users: false
  timeout: 1200
  every: 120
