#!/usr/bin/env bash

# zones
ZONE=us-east4-a
REGION=us-east4

# delete jupyter release
echo "Deleting jupyter ... "
helm delete jupyter --purge
echo

# delete jupyter namespace
echo "Deleting jupyter namespace ..."
kubectl delete namespace jupyter
echo

# delete cluster
gcloud container clusters delete pangeo --zone $ZONE --quiet
echo

# delete disks
echo "Deleting all disks ... "
gcloud compute disks list | grep -v ^NAME | sed 's/  */ /g' | cut -d' ' -f1 | \
  xargs gcloud compute disks delete --quiet --zone=$ZONE
echo

# delete forwarding-rules
echo "Deleting all forwarding-rules ... "
gcloud compute forwarding-rules list | grep -v ^NAME | sed 's/  */ /g' | cut -d' ' -f1 | \
  xargs gcloud compute forwarding-rules delete --quiet --region=$REGION
echo

# delete target-pools
echo "Deleting all target-pools ... "
gcloud compute target-pools list | grep -v ^NAME | sed 's/  */ /g' | cut -d' ' -f1 | \
  xargs gcloud compute target-pools delete --quiet --region=$REGION

# delete vpc network firewall-rules
gcloud compute firewall-rules list --format=yaml | grep ^name | cut -d' ' -f2 | \
  xargs gcloud compute firewall-rules delete --quiet
